### ISSUE TITLE
Problems with new photon update

### ISSUE THREAD

**Issue by Inesgor** [aadilayub/firefox-i3wm-theme#4]
Assalaamu Alaikum.
I really like this theme (y). However, now with the new UI update of Firefox, this no longer seems usable. 
I would be kind of you to make the necessary changes.
Thank you.

**Comment by rettetdemdativ** [comment]
I implemented a potential fix (this is what worked for me) in #5 .

**Comment by alizehctl** [comment]
@Inesgor thanks for reporting! I haven't got the photon update on my distro yet so didn't notice the breaking change. 

@rettetdemdativ tyvm for the PR! I'll test it out as soon as the new firefox lands in the fedora repos.

**Comment by alizehctl** [comment]
merged @rettetdemdativ's PR. This makes the theme functional again
