### ISSUE TITLE
Yeah something went wrong with the tab and I don't know why

### ISSUE THREAD

**Issue by i34sti1337** [aadilayub/firefox-i3wm-theme#8]
Here is a picture of my internet explorer right now 

![2022-08-25-170932_2560x1440_scrot](https://user-images.githubusercontent.com/112108718/186717542-97674ffe-6fa8-4294-95b3-fe0056d508d3.png)

**Comment by alizehctl** [comment]
That's strange. Did you follow all the instructions in the README?

**Comment by i34sti1337** [comment]
I found the solution. It was the Firefox theme. Great Job btw.
One Question i have though, how can i make the bar bigger? so it looks like my main bar on the bottom?

**Comment by alizehctl** [comment]
Thanks! You could try editing [this line](https://github.com/aadilayub/firefox-i3wm-theme/blob/927a6b63aeaf5ebd9b2e3566813248a5ffeaa9c6/userChrome.css#L11) - although this whole theme is a collection of css hacks and I can't guarantee that you won't have to tweak the css more to acheive your desired effect.
